### ISSUE TITLE
[Solved] Build on Ubuntu 20.04 failed

### ISSUE THREAD

**Issue by kaklik** [ghostop14/gr-grnet#15]
The make install step, produce the following: 

    gr-grnet/lib/ComplexToSC16_impl.cc:690:36: error: could not convert ‘gnuradio::get_initial_sptr(T*) [with T =   gr::grnet::ComplexToSC16_impl]()’ from ‘boost::shared_ptr<gr::grnet::ComplexToSC16_impl>’ to ‘gr::grnet::ComplexToSC16::sptr’  {aka ‘std::shared_ptr<gr::grnet::ComplexToSC16>’}
    690 |   return gnuradio::get_initial_sptr(new ComplexToSC16_impl());
          |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
          |                                    |
          |                                    boost::shared_ptr<gr::grnet::ComplexToSC16_impl>

**Comment by ghostop14** [comment]
The branches in gr-net match up with gnuradio and that shared_ptr error is related to mixing code currently matching GR master with older versions.  Try checking out the maint-3.8 (assuming you're on gnuradio 3.8) branch and see if that takes care of it for you.

**Comment by kaklik** [comment]
Use of maint-3.8 branch solved the issue. 

Thanks!
